Ipc enhanced
Skaginn3x/framework pull request #150
Opened 2023-09-08 08:54 UTC by jbbjarnason

2023-09-08 15:15 UTC, omarhogni requested changes

2023-09-08 15:15 UTC, omarhogni commented on libs/ipc/inc/public/tfc/ipc/item.hpp
> +                                           "entry", &type::entry, "Entry time of item entering the scope of tfc",
of tfc?

2023-09-08 15:15 UTC, omarhogni commented on libs/stx/inc/public/tfc/stx/glaze_meta.hpp
> +
Maybe add a test for this

2023-09-08 15:31 UTC, jbbjarnason commented on cmake/tfc_options.cmake
> +#add_compile_definitions(BOOST_ASIO_NO_DEPRECATED=1)
removed

2023-09-08 15:31 UTC, jbbjarnason commented on exes/tfcctl/src/tfcctl.cpp
> +  std::vector<std::string> connections;
rollbacked refactor

2023-09-08 15:32 UTC, jbbjarnason commented on exes/tfcctl/src/tfcctl.cpp
> +        logger.info("{}: {}", sig, val);  //
one lined

2023-09-08 15:33 UTC, jbbjarnason commented on exes/tfcctl/src/tfcctl.cpp
> +              in_logger.error("Failed to connect: {}", error.message());
now as warning

2023-09-11 07:44 UTC, jbbjarnason commented on libs/confman/src/detail/config_dbus_client.cpp
> +inline constexpr std::string_view change_dots_preceding_number_to{ "(\\.)+(?=\\d)" };
if these were to be at fault the implications would be minor, the sd-bus abi rejecting the string.

fyi, https://regex101.com/r/zl74gE/1

2023-09-11 08:54 UTC, jbbjarnason commented on libs/ipc/inc/public/tfc/ipc/item.hpp
> +
@omarhogni I have not made a complete set of tests but you can now see how this is broken. see lines 132-139

2023-09-11 12:27 UTC, jbbjarnason commented on libs/ipc/inc/public/tfc/ipc/item.hpp
> +  std::string origin{};
Made it a bit more explicit but it could be better with an enum

2023-09-11 12:29 UTC, jbbjarnason commented on libs/ipc/inc/public/tfc/ipc/item.hpp
> +  // This offset is kind of ridiculous, as in the - 1
changed the comment a bit, making it a bit less harsh.
added a test case showing this error

2023-09-11 12:57 UTC, jbbjarnason commented on libs/ipc/inc/public/tfc/ipc/item.hpp
> +  static constexpr auto from_int(std::uint16_t input) -> species {
now returning optional to handle error cases

2023-09-11 13:05 UTC, jbbjarnason commented on libs/ipc/inc/public/tfc/ipc/item.hpp
> +  std::optional<std::chrono::system_clock::time_point> entry{ std::nullopt };  // when did item enter system
changed to entry_timestamp

2023-09-11 13:05 UTC, jbbjarnason commented on libs/ipc/inc/public/tfc/ipc/item.hpp
> +  std::optional<std::string> destination{ std::nullopt };
changed to empty struct, to be continued

2023-09-11 13:08 UTC, jbbjarnason commented on libs/ipc/inc/public/tfc/ipc/item.hpp
> +//                                           "temperature", &type::temperature, "Temperature in celsius",
I would like to keep it to remind me of implementing it later on

2023-09-11 13:08 UTC, jbbjarnason commented on libs/ipc/inc/public/tfc/ipc/item.hpp
> +                                           "entry", &type::entry, "Entry time of item entering the scope of tfc",
changed tfc to system

2023-09-11 13:18 UTC, jbbjarnason commented on libs/ipc/tests/item_test.cpp
> +    fmt::print("foo is: {}\n", foo.code.view());
I will enhance the tests a bit while I use the item class as it would be cumbersome writing encoding tests and change the item struct

2023-09-11 14:41 UTC, jbbjarnason commented on libs/progbase/src/progbase.cpp
> +  std::filesystem::path filename_path{ filename_cp };
removed and is now part of dbus string creation methods

2023-09-12 15:54 UTC, omarhogni commented on libs/confman/src/detail/config_dbus_client.cpp
> +inline constexpr std::string_view change_dots_preceding_number_to{ "(\\.)+(?=\\d)" };
this misses this case ```8.input``` which is invalid.

2023-09-13 11:47 UTC, jbbjarnason commented on libs/confman/src/detail/config_dbus_client.cpp
> +inline constexpr std::string_view change_dots_preceding_number_to{ "(\\.)+(?=\\d)" };
I would not prefer this expression capturing more then it is intended for. 
This should currently cover `<text>.<number>`

I would suggest that starting with a number would be a different expression

2023-09-14 19:11 UTC, jbbjarnason commented on libs/stx/inc/public/tfc/stx/glaze_meta.hpp
> +
done

2023-09-14 19:11 UTC, jbbjarnason commented on libs/snitch/snitch.hpp
> +}  // namespace tfc::snitch
removed

2023-09-15 13:08 UTC, omarhogni approved these changes
Viltu hafa fmt hérna en ekki inná vcpkg-repository,

ef þetta er svona þá er ekki hægt að builda hluti sem nota tfc

2023-09-15 15:03 UTC, jbbjarnason commented
> Viltu hafa fmt hérna en ekki inná vcpkg-repository,
> 
> ef þetta er svona þá er ekki hægt að builda hluti sem nota tfc

Já þar sem það verður inni í svona viku, þar til fmt pullan verður komin inn

2023-09-15 15:04 UTC, jbbjarnason commented on exes/gpio/src/gpio.cpp
> +      pins_.at(idx).emplace<ipc_input_t>(ctx_, manager_client_, fmt::format("in.{}", idx),
should be fixed when gpio exe will be fixed, as it is not working yet

2023-09-15 15:05 UTC, omarhogni commented
Má þá ekki keyra þetta inn bara?

2023-09-15 15:50 UTC, merged